import { BrainCircuit, Database, Info, Map, Radio, Route, ShieldCheck, Users, X } from 'lucide-react';

interface Props { open: boolean; onClose: () => void; }
export default function DataTransparency({ open, onClose }: Props) {
  if (!open) return null;
  const rows = [
    { icon: Radio, label: 'Telecom sites', value: 'Simulated geospatial asset data' },
    { icon: Route, label: 'Road network', value: 'Simulated Greater Kuala Lumpur road network' },
    { icon: Map, label: 'Traffic', value: 'Simulated traffic conditions and road accessibility' },
    { icon: Database, label: 'Maintenance', value: 'Synthetic maintenance history and site health indicators' },
    { icon: Users, label: 'Technicians', value: 'Simulated availability, skills, and workload profiles' },
    { icon: BrainCircuit, label: 'GeoAI methods', value: 'Prototype risk scoring, proximity analysis, clustering, routing, ETA, and matching' },
  ];
  return <div className="fixed inset-0 z-[2000] flex items-center justify-center p-4" style={{ background: 'rgba(2,6,23,0.62)' }}><div className="card w-full max-w-lg max-h-[85vh] overflow-y-auto animate-scale-in"><div className="flex items-center justify-between px-5 py-4 border-b sticky top-0" style={{ borderColor: 'var(--surface-border)', background: 'var(--bg-elev)' }}><div className="flex items-center gap-2"><ShieldCheck size={18} className="text-primary-500" /><div><h3 className="text-sm font-semibold">Data & GeoAI Information</h3><p className="text-xs muted-text">Transparency for prototype demonstration</p></div></div><button onClick={onClose} className="p-1 muted-text hover:text-[var(--text)]"><X size={18} /></button></div><div className="p-5 space-y-2">{rows.map(({ icon: Icon, label, value }) => <div key={label} className="flex items-center gap-3 rounded-lg p-3" style={{ background: 'var(--bg-soft)', border: '1px solid var(--surface-border)' }}><Icon size={16} className="text-primary-500 shrink-0" /><div><p className="text-xs font-semibold">{label}</p><p className="text-xs muted-text mt-0.5">{value}</p></div></div>)}<div className="rounded-lg p-3 mt-3" style={{ background: 'rgba(37,99,235,0.07)', border: '1px solid rgba(37,99,235,0.2)' }}><p className="text-xs font-semibold text-primary-600">Prototype honesty</p><p className="text-xs soft-text leading-relaxed mt-1">Prototype data is simulated for demonstration. Real telecom, GIS, road network, traffic, maintenance, and technician datasets can be integrated in a future deployment. This prototype does not claim production AI accuracy, real-time GPS, or live traffic data.</p></div><div className="rounded-lg p-3 mt-2" style={{ border: '1px solid var(--surface-border)' }}><p className="text-xs font-semibold mb-2 flex items-center gap-1.5"><Info size={13} className="text-secondary-600" /> Why GeoAI?</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div className="rounded-lg p-2.5" style={{ background: 'var(--bg-soft)' }}><p className="text-[10px] muted-text uppercase mb-1">Traditional</p><p className="text-xs soft-text leading-relaxed">Site → Work Order → Technician → Route</p><p className="text-[10px] muted-text mt-1.5">Linear, reactive, no spatial intelligence.</p></div><div className="rounded-lg p-2.5" style={{ background: 'rgba(37,99,235,0.05)', border: '1px solid rgba(37,99,235,0.15)' }}><p className="text-[10px] text-primary-600 uppercase mb-1">GeoRouteAI</p><p className="text-xs soft-text leading-relaxed">Site + Condition + History + Tech Location + Road Network + Traffic + SLA → GeoAI Decision Engine → Optimal Plan</p><p className="text-[10px] text-primary-600 mt-1.5">Spatial, predictive, explainable, adaptive.</p></div></div></div></div></div></div>;
}
